views.py
from flask import Flask, render_template, redirect, url_for, session, flash, request, jsonify, Blueprint
import bcrypt
import requests
import base64
from datetime import datetime
import json
from forms import RegisterForm, LoginForm, ForgotPasswordForm, ForgotPasswordForm, ResetPasswordForm
from utils.utils import get_access_token, initiate_stk_push ,connect_to_database, generate_reset_token,send_reset_email
import requests, uuid, json
import random
import os
import time
from dotenv import load_dotenv
from itsdangerous import URLSafeTimedSerializer
from flask import request, current_app as app, url_for
import logging
import subprocess
from werkzeug.utils import secure_filename


load_dotenv()
tag = os.getenv('TAG')
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


views = Blueprint("views",__name__)

@views.route('/threat')
def run_streamlit():
    subprocess.run(["streamlit", "run", "./stride-gpt/main.py"])
    return "threat model is running..."

@views.app_errorhandler(404)
def not_found_error(error):
    return render_template('404.html', title='License.io | Not Found'), 404

@views.route('/')
def index():
    get_access_token()
    return render_template('home.html', title='License.io | Home')

@views.route('/pricing')
def pricing():
    return render_template('pricing.html', title='License.io | Pricing')

@views.route('/about')
def about():
    return render_template('about.html', title='License.io | About')

@views.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

        conn = connect_to_database()
        cur = conn.cursor()

        try:
            cur.execute("INSERT INTO users (name, email, password) VALUES (%s, %s, %s)", (name, email, hashed_password))
            conn.commit()
        except Exception as e:
            conn.rollback()
            flash("An error occurred while registering: {}".format(str(e)), 'error')
            return redirect(url_for('views.register'))
        finally:
            cur.close()
            conn.close()

        flash('Registration successful. You can now log in.', 'success')
        return redirect(url_for('views.login'))

    return render_template('register.html', form=form, title='License.io | Register')


@views.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        with connect_to_database().cursor() as cur:
            cur.execute("SELECT * FROM users WHERE email=%s", (email,))
            user = cur.fetchone()

            if user and bcrypt.checkpw(password.encode('utf-8'), user['password'].encode('utf-8')):
                session['user_id'] = user['id']
                if user['is_super_user']:
                    return redirect(url_for('views.admin'))
                else:
                    flash("You have logged in successfully.")
                    return redirect(url_for('views.dashboard'))
            else:
                flash("Login failed. Please check your email and password")
                return redirect(url_for('views.login'))

    return render_template('login.html', form=form, title='License.io | Login')

@views.route('/admin')
def admin():
    if 'user_id' in session:
        user_id = session['user_id']
        connection = connect_to_database()
        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))
                user = cursor.fetchone()
                
                if user:
                    user_name = user['name']
                    cursor.execute("SELECT COUNT(*) FROM users WHERE is_super_user = 0")
                    registered_users_count = cursor.fetchone()['COUNT(*)']
                    
                    cursor.execute("SELECT SUM(Amount) FROM transaction")
                    total_amount = cursor.fetchone()['SUM(Amount)']
                    
                    return render_template('adminpanel.html', user=user, user_name=user_name, title='License.io | Admin', registered_users_count=registered_users_count, total_amount=total_amount)
        finally:
            connection.close()
            
    return redirect(url_for('views.login'))


    
@views.route('/dashboard')
def dashboard():
    if 'user_id' in session:
        user_id = session['user_id']

        with connect_to_database().cursor() as cur:
            cur.execute("SELECT * FROM users where id=%s", (user_id,))
            user = cur.fetchone()

        if user:
            user_name = user['name']
            return render_template('dashboard.html', user=user, user_name=user_name,title='License.io | Dashboard')

    return redirect(url_for('login'))


@views.route('/logout')
def logout():
    session.pop('user_id', None)
    flash("You have been logged out successfully.")
    return redirect(url_for('views.index'))


@views.route("/initiate", methods=['POST'])
def initiate():
    phone_number = request.json.get('phone')
    result = initiate_stk_push(phone_number) 
    if 'error' in result:
        return jsonify({'error': result['error']}), 500 
    else:
        return jsonify({'[itskios-09]': 'STK push initiated successfully', 'CheckoutRequestID': result['CheckoutRequestID']}), 200 
    
@views.route("/forgot_password", methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        connection = connect_to_database()
        try:
            with connection.cursor() as cursor:
                sql_check_email = "SELECT * FROM users WHERE email=%s"
                cursor.execute(sql_check_email, (email,))
                user = cursor.fetchone()
                if user:
                    token = generate_reset_token(email)
                    send_reset_email(email, token)
                    flash('Password reset link has been sent to your email')
                else:
                    flash('Email does not exist')
        finally:
            connection.close()
        
        return redirect(url_for('views.forgot_password'))

    return render_template('forgot_password.html', form=form, title='License.io | Forgot Password')



@views.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    try:
        email = serializer.loads(token, salt=app.config['SECURITY_PASSWORD_SALT'], max_age=3600)
    except:
        flash('The reset link is invalid or has expired')
        return redirect(url_for('views.forgot_password'))  
    
    form = ResetPasswordForm()  
    if form.validate_on_submit():
        new_password = form.password.data
        hashed_password = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt())
        connection = connect_to_database()
        try:
            with connection.cursor() as cursor:
                sql_check_email = "SELECT * FROM users WHERE email=%s"
                cursor.execute(sql_check_email, (email,))
                user = cursor.fetchone()
                if user:
                    sql_update_password = "UPDATE users SET password=%s WHERE email=%s"
                    cursor.execute(sql_update_password, (hashed_password.decode('utf-8'), email))
                    connection.commit()
                    flash('Your password has been updated')
                    return redirect(url_for('views.login'))  
                else:
                    flash('Email does not exist')
                    return redirect(url_for('views.forgot_password'))  
        finally:
            connection.close()
    
    return render_template('reset_password.html', form=form, title='License.io | Reset Password', token=token)

@views.route('/verify', methods=['POST'])
def verify_receipt():
    connection = connect_to_database()
    try:
        data = request.json
        mpesa_receipt_number = data.get('mpesa_receipt_number', '').upper() 
        with connection.cursor() as cursor:
            sql_check_receipt = "SELECT * FROM transaction WHERE MpesaReceiptNumber = %s AND is_verified = 1"
            cursor.execute(sql_check_receipt, (mpesa_receipt_number,))
            receipt = cursor.fetchone()
            if receipt:
                response = jsonify({'message': 'M-Pesa receipt number already verified'})
                logging.info(f'{tag}: M-Pesa receipt number already verified: %s', response.json)
                return response, 200
            else:
                sql_update_receipt = "UPDATE transaction SET is_verified = 1 WHERE MpesaReceiptNumber = %s"
                cursor.execute(sql_update_receipt, (mpesa_receipt_number,))
                connection.commit()
                affected_rows = cursor.rowcount
                if affected_rows > 0:
                    response = jsonify({'message': 'M-Pesa receipt number verified successfully'})
                    logging.info(f'{tag}: M-Pesa receipt number verified successfully: %s', response.json)
                    return response, 200
                else:
                    response = jsonify({'message': 'Kindly make payment first'})
                    logging.info(f'{tag}: Receipt not found: %s', response.json)
                    return response, 404
    except Exception as e:
        response = jsonify({'message': str(e)})
        logging.error('Error verifying receipt: %s', response.json)
        return response, 500
    finally:
        connection.close()
        
@views.route('/process_request', methods=['POST'])
def process_request():
    connection = connect_to_database()
    mpesa_receipt = request.form['mpesa'].upper()

templates/about.html
{% extends 'base.html' %} {% block content %}
<section id="about" class="about">
  <div class="container">
    <div class="row content" style="margin-top: 80px">
      <div class="col-lg-6">
        <h2>Software Piracy Protection System</h2>
        <h3>
          Our cutting-edge software licensing solution provides a comprehensive
          suite of benefits aimed at optimizing your operations and enhancing
          customer satisfaction.
        </h3>
      </div>
      <div class="col-lg-6 pt-4 pt-lg-0">
        <p>
          We're dedicated to empowering African developers with the tools and
          resources needed to effectively manage software licenses. We
          understand the importance of proper license management in optimizing
          operations and ensuring compliance. Our goal is to provide accessible
          and user-friendly software license management solutions tailored to
          the needs of African markets.<br />
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/adminpanel.html
{% extends 'dashbase.html' %} {% block content %}

<div class="container">
  {% if user %}

  <main id="main" class="main">
    <div class="pagetitle">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Welcome</li>
          <li class="breadcrumb-item active">{{ user_name }}</li>
        </ol>
      </nav>
    </div>

    <section class="section dashboard">
      <div class="row">
        <div class="col-lg-4">
          <div class="card info-card key-card">
            <div class="card-body">
              <h5 class="card-title"><span>| Registered Users</span></h5>
              <p style="font-size: 15px; color: #000">
                {{registered_users_count }} users
              </p>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card info-card upload-card">
            <div class="card-body">
              <h5 class="card-title"><span>| Total Revenue Collected</span></h5>
              <p style="font-size: 15px; color: #000">Ksh {{total_amount }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endif %} {% endblock%}
  </main>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ title }}</title>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bot.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
  </head>
  <body>
    <div class="landing-page">
      <header>
        <div class="container">
          <a href="{{ url_for('views.index') }}" class="logo">License.io</a>
          <ul class="links">
            <li><a href="{{ url_for('views.index') }}">Home</a></li>
            <li><a href="{{ url_for('views.pricing') }}">Pricing</a></li>
            <li>
              <a
                href="{{ url_for('views.login') }}"
                class="get-started white-text"
                >Login</a
              >
            </li>
          </ul>
        </div>
      </header>
    </div>
    {% block content %}{% endblock %}
  </body>
</html>

templates/cards.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style></style>
  </head>
  <body>
    <section class="cards">
      <article class="cardie card--1">
        <div class="card__info-hover">
          <svg class="card__like" viewBox="0 0 24 24">
            <path
              fill="#000000"
              d="M12.1,18.55L12,18.65L11.89,18.55C7.14,14.24 4,11.39 4,8.5C4,6.5 5.5,5 7.5,5C9.04,5 10.54,6 11.07,7.36H12.93C13.46,6 14.96,5 16.5,5C18.5,5 20,6.5 20,8.5C20,11.39 16.86,14.24 12.1,18.55M16.5,3C14.76,3 13.09,3.81 12,5.08C10.91,3.81 9.24,3 7.5,3C4.42,3 2,5.41 2,8.5C2,12.27 5.4,15.36 10.55,20.03L12,21.35L13.45,20.03C18.6,15.36 22,12.27 22,8.5C22,5.41 19.58,3 16.5,3Z"
            />
          </svg>
          <div class="card__clock-info">
            <svg
              fill="#000000"
              height="15px"
              width="15px"
              version="1.1"
              id="Capa_1"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              viewBox="0 0 173.312 173.312"
              xml:space="preserve"
              stroke="#000000"
            >
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g
                id="SVGRepo_tracerCarrier"
                stroke-linecap="round"
                stroke-linejoin="round"
              ></g>
              <g id="SVGRepo_iconCarrier">
                <polygon
                  points="137.078,102.745 36.234,0 36.238,143.965 65.559,118.501 87.965,173.312 120.72,159.922 98.315,105.112 "
                ></polygon>
              </g>
            </svg>
            <span class="card__time">5 clicks</span>
          </div>
        </div>
        <div class="card__img"></div>
        <a href="" class="card_link">
          <div class="card__img--hover"></div>
        </a>
        <div class="card__info">
          <span class="card__category"> Google chrome</span>
          <h3 class="card__title">Download</h3>
          <!-- <span class="card__by">by <a href="#" class="card__author" title="author">Celeste Mills</a></span> -->
        </div>
      </article>
    </section>
  </body>
</html>

templates/dashbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="../static/vendor/boxicons/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      href="../static/vendor/glightbox/css/glightbox.min.css"
      rel="stylesheet"
    />
    <link href="../static/vendor/remixicon/remixicon.css" rel="stylesheet" />
    <link href="static/css/main.css" rel="stylesheet" type="text/css" />
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/boxicons/2.0.7/css/boxicons.min.css"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="landing-page">
      <header>
        <div class="container">
          <a href="#" class="logo">Dashboard</a>
          <ul class="links">
            <li>
              <a
                href="{{ url_for('views.logout') }}"
                class="get-started white-text"
                >Log out</a
              >
            </li>
          </ul>
        </div>
      </header>
    </div>

    {% block content %} {% endblock %}
  </body>
</html>

templates/dashboard.html
{% extends 'dashbase.html' %} {% block content %}

<div class="container">
  {% if user %}

  <main id="main" class="main">
    <div class="pagetitle">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Welcome</li>
          <li class="breadcrumb-item active">{{ user_name }}</li>
        </ol>
      </nav>
    </div>
    <div id="alerts"></div>
    <section class="section dashboard">
      <div class="row">
        <div class="col-lg-4">
          <div class="card info-card key-card">
            <div class="card-body">
              <h5 class="card-title">Step 1 <span>| Purchase API Key</span></h5>
              <div class="d-flex align-items-center">
                <button type="button" class="btn btn-primary" id="show-pay">
                  Purchase API Key
                  <i class="bx bx-key" style="font-size: 18px"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="popup">
          <div class="close-btn">&times;</div>
          <div class="form">
            <div class="form-element">
              <label for="phone">Phone Number</label>
              <input
                type="text"
                id="phone"
                placeholder="Enter phone number: 254XXXXXXXXX"
                autocomplete="off"
              />
            </div>
            <div class="form-element">
              <button id="sendRequest">Send request</button>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card info-card upload-card">
            <div class="card-body">
              <h5 class="card-title">
                Step 2 <span>| Verify Your Payment</span>
              </h5>
              <div class="d-flex align-items-center">
                <button type="button" class="btn btn-info" id="show-verify">
                  Verify Your Payment
                  <i class="bx bx-upload" style="font-size: 18px"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="popup-verify">
          <div class="close-btn">&times;</div>
          <div class="form">
            <div class="form-element">
              <label for="mpesa">Receipt Number</label>
              <input
                type="text"
                id="mpesa"
                placeholder="Verify Your Mpesa Receipt Number: SBP65IWM7M"
                autocomplete="off"
              />
            </div>
            <div class="form-element">
              <button id="verify">Verify</button>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card info-card download-card">
            <div class="card-body">
              <h5 class="card-title">Step 3 <span>| Select API Key</span></h5>
              <div class="d-flex align-items-center">
                <button
                  type="button"
                  class="btn btn-success"
                  id="show-download"
                >
                  Download API Keys
                  <i
                    class="bx bx-download"
                    style="font-size: 24px; margin-left: 8px"
                  ></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="popup-download">
          <div class="close-btn">&times;</div>
          <div class="form">
            <div class="form-element">
              <label for="mpesa"> Verified Receipt Number</label>
              <input
                type="text"
                id="mpesa-verified"
                placeholder="Enter Verified Mpesa Receipt Number: SBP65IWM7M"
                autocomplete="off"
              />
            </div>
            <label for="mpesa" style="color: #000">API Keys</label>
            <div class="container-dropdown">
              <div
                class="wrapper-dropdown"
                id="myDropdown"
                style="width: 320px"
              >
                <span>Choose API key</span>
                <ul class="dropdown">
                  <li>OpenAI key</li>
                </ul>
              </div>
            </div>
            <div class="form-element">
              <button id="download-api">Download API Key</button>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card info-card download-card">
            <div class="card-body">
              <h5 class="card-title">Step 4 <span>| Threat Modelling</span></h5>
              <div class="d-flex align-items-center">
                <button
                  type="button"
                  class="btn btn-success"
                  onclick="window.location.href='/threat'"
                >
                  Threat modelling
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endif %}
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

    {% endblock%}
  </main>
</div>

templates/forgot_password.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center"> 
    <div class="col-md-6">
      <h4 style="margin-top: 150px;">Forget your password</h4>
  
      {% with messages = get_flashed_messages() %}
      {% if messages %}
          <div class="alert alert-danger">
              <ul>
                  {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
              </ul>
          </div>
      {% endif %}
      {% endwith %}

      <form action="{{ url_for('views.forgot_password') }}" method="POST" class="form-center">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(for="email")}}
            {{ form.email(id="email", class="form-control")}}
      
            {% if form.email.errors %}
                  <ul>
                      {% for error in form.email.errors %}
                          <li>{{ error }}</li>
                      {% endfor %}
                  </ul>
            {% endif %}
        </div>
        {{ form.submit(class="btn btn-dark mt-4")}}
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="landing-page">
  <div class="content">
    <div class="container">
      <div class="info">
        <h1>Software piracy protection system</h1>
        <p>
          software piracy protection system offers oftware licensing solution
          provides a comprehensive suite of benefits aimed at optimizing your
          operations and enhancing customer satisfaction
        </p>
        <button onclick="window.location.href='/about'" class="btn btn-info">
          More About Us
        </button>
      </div>
      <div class="image">
        <img src="../static/img/Background.png" />
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <!-- Center the content -->
    <div class="col-md-6">
      <h4 style="margin-top: 150px">Login</h4>

      {% with messages = get_flashed_messages() %} {% if messages %}
      <div class="alert alert-danger">
        <ul>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %} {% endwith %}

      <form
        action="{{ url_for('views.login') }}"
        method="POST"
        class="form-center"
      >
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.email.label(for="email")}} {{ form.email(id="email",
          class="form-control")}} {% if form.email.errors %}
          <ul>
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label(for="password")}} {{
          form.password(id="password", class="form-control")}} {% if
          form.password.errors %}
          <ul>
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-dark mt-4")}}
        <a href="{{ url_for('views.register') }}" class="btn btn-secondary mt-4"
          >Register page</a
        >
        <br />
        <br /><a href="{{ url_for('views.forgot_password') }}"
          >Forgot your password?</a
        >
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/pricing.html
{% extends 'base.html' %} {% block content %}

<section id="pricing" class="pricing" style="margin-top: 100px">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Pricing</h2>
    </div>

    <div class="row">
      <div
        class="col-lg-4 mt-4 mt-lg-0"
        data-aos="fade-up"
        data-aos-delay="300"
      >
        <div class="box">
          <h3>Silver Plan</h3>
          <h4><sup>Ksh </sup>1000<span>per month</span></h4>
          <ul>
            <li><i class="bx bx-check"></i>Full Protected</li>
          </ul>
          <a href="{{ url_for('views.login') }}" class="buy-btn">Get Started</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/register.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <!-- Center the content -->
    <div class="col-md-6">
      <h4 style="margin-top: 150px">Sign up</h4>
      <form action="{{ url_for('views.register') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.name.label(for="name")}} {{ form.name(id="name",
          class="form-control")}} {% if form.name.errors %}
          <ul class="text-danger">
            {% for error in form.name.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.email.label(for="email")}} {{ form.email(id="email",
          class="form-control")}} {% if form.email.errors %}
          <ul class="text-danger">
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label(for="password")}} {{
          form.password(id="password", class="form-control")}} {% if
          form.password.errors %}
          <ul class="text-danger">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-dark mt-4")}}
        <a href="{{ url_for('views.login') }}" class="btn btn-secondary mt-4"
          >Login page</a
        >
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/reset_password.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center"> 
    <div class="col-md-6">
      <h4 style="margin-top: 150px;">Reset your password</h4>
  
      {% with messages = get_flashed_messages() %}
      {% if messages %}
          <div class="alert alert-danger">
              <ul>
                  {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
              </ul>
          </div>
      {% endif %}
      {% endwith %}

      <form action="{{ url_for('views.reset_password', token=token) }}" method="POST" class="form-center">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password.label(for="password")}}
            {{ form.password(id="password", class="form-control")}}
      
            {% if form.password.errors %}
                  <ul>
                      {% for error in form.password.errors %}
                          <li>{{ error }}</li>
                      {% endfor %}
                  </ul>
            {% endif %}
        </div>
        {{ form.submit(class="btn btn-dark mt-4")}}
      </form>
    </div>
  </div>
</div>
{% endblock %}